			<div class="last-game-bar col-md-12 col-sm-12 col-xs-12">
					<div class="row justify-content-md-end">
						<div class="block col-md-12 col-sm-12 col-xs-12">
							<h3>Последние действия</h3>
							<table align="center" class="col-md-12 col-sm-12 col-xs-12">
								<tr>
									<th>Комната</th>
									<th>Имя</th>
									<th>Сумма</th>
									<th>Тип</th>
									<th>LVL</th>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>
								<tr>
									<td>548789</td>
									<td>Эдуард</td>
									<td>300</td>
									<td>PRO</td>
									<td>5</td>
								</tr>
								<tr>
									<td>157987</td>
									<td>Абрахам</td>
									<td>600</td>
									<td>PRO</td>
									<td>8</td>
								</tr>
								<tr>
									<td>9875464</td>
									<td>Микаса</td>
									<td>40</td>
									<td>Free</td>
									<td>3</td>
								</tr>


							</table>
						</div>
					</div>
				</div>